language: java

script:
    - gradle build

jdk:
    - oraclejdk8

before_install:
    - wget http://www.antlr.org/download/antlr-4.5.3-complete.jar
    - java -jar antlr-4.5.3-complete.jar vrjass.g4 -no-listener -visitor -o src/main/java/com/ruke/vrjassc/vrjassc/antlr4 -package com.ruke.vrjassc.vrjassc.antlr4 -encoding UTF-8