language: java

script:
    - gradle build

jdk:
    - oraclejdk8

before_install:
    - wget http://www.antlr.org/download/antlr-4.5.3-complete.jar
    - export CLASSPATH=".:/usr/local/lib/antlr-4.5.3-complete.jar:$CLASSPATH"
    - alias antlr4='java -jar /usr/local/lib/antlr-4.5.3-complete.jar'
    - antlr4 vrjass.g4 -no-listener -visitor -o src/main/java/com/ruke/vrjassc/vrjassc/antlr4 -package com.ruke.vrjassc.vrjassc.antlr4 -encoding UTF-8